const deckNobles = [];

const discardNobles = [];

class Noble {
	constructor(name, points, color){
		this.name = name;
		this.points = points;
		this.color = color; 
	}
}

const archbishop = new Noble('Archbishop', 4, 'blue');
deckNobles.push(archbishop);
const baron = new Noble('Baron', 3, 'purple');
deckNobles.push(baron);
const bishop = new Noble('Bishop', 2, 'blue');
deckNobles.push(bishop);
const captain = new Noble('Captain of the Guard', 2, 'red');
deckNobles.push(captain);
const cardinal = new Noble('Cardinal', 5, 'blue');
deckNobles.push(cardinal);
const cartographer = new Noble('Royal Cartographer', 1, 'purple');
deckNobles.push(cartographer);
const coiffeur = new Noble('Coiffeur', 1, 'purple');
deckNobles.push(coiffeur);
const colonel = new Noble('Colonel', 3, 'red');
deckNobles.push(colonel);
const councilman = new Noble('Councilman', 3, 'green');
deckNobles.push(councilman);
const count = new Noble('Count', 2, 'purple');
deckNobles.push(count);
const countess = new Noble('Countess', 2, 'purple');
deckNobles.push(countess);
const clown = new Noble('Clown', -2, 'gray');
deckNobles.push(clown);
const duke = new Noble('Duke', 3, 'purple');
deckNobles.push(duke);
const fast = new Noble('Fast Noble', 2, 'purple');
deckNobles.push(fast);
const general = new Noble('General', 4, 'red');
deckNobles.push(general);
const governor = new Noble('Governor', 4, 'green');
deckNobles.push(governor);
const guardOne = new Noble('Palace Guard 1', 1, 'red');
deckNobles.push(guardOne);
const guardTwo = new Noble('Palace Guard 2', 1, 'red');
deckNobles.push(guardTwo);
const guardThree = new Noble('Palace Guard 3', 1, 'red');
deckNobles.push(guardThree);
const guardFour = new Noble('Palace Guard 4', 1, 'red');
deckNobles.push(guardFour);
const guardFive = new Noble('Palace Guard 5', 1, 'red');
deckNobles.push(guardFive);
const heretic = new Noble('Heretic', 2, 'blue');
deckNobles.push(heretic);
const hero = new Noble('Hero of the People', -3, 'gray');
deckNobles.push(hero);
const judgeOne = new Noble('Unpopular Judge 1', 2, 'green');
deckNobles.push(judgeOne);
const judgeTwo = new Noble('Unpopular Judge 2', 2, 'green');
deckNobles.push(judgeTwo);
const king = new Noble('King Louis XVI', 5, 'purple');
deckNobles.push(king);
const lady = new Noble('Lady', 2, 'purple');
deckNobles.push(lady);
const ladyWaiting = new Noble('Lady in Waiting', 1, 'purple');
deckNobles.push(ladyWaiting);
const landlord = new Noble('Landlord', 2, 'green');
deckNobles.push(landlord);
const lieutenantOne = new Noble('Lieutenant 1', 2, 'red');
deckNobles.push(lieutenantOne);
const lieutenantTwo = new Noble('Lieutenant 2', 2, 'red');
deckNobles.push(lieutenantTwo);
const lord = new Noble('Lord', 2, 'purple');
deckNobles.push(lord);
const martyrOne = new Noble('Martyr 1', -1, 'gray');
deckNobles.push(martyrOne);
const martyrTwo = new Noble('Martyr 2', -1, 'gray');
deckNobles.push(martyrTwo);
const martyrThree = new Noble('Martyr 3', -1, 'gray');
deckNobles.push(martyrThree);
const mayor = new Noble('Mayor', 3, 'green');
deckNobles.push(mayor);
const nun = new Noble('Bad Nun', 3, 'blue');
deckNobles.push(nun);
const pissBoy = new Noble('Piss Boy', 1, 'purple');
deckNobles.push(pissBoy);
const priestOne = new Noble('Wealthy Priest 1', 1, 'blue');
deckNobles.push(priestOne);
const priestTwo = new Noble('Wealthy Priest 2', 1, 'blue');
deckNobles.push(priestTwo);
const queen = new Noble('Marie Antoinette', 5, 'purple');
deckNobles.push(queen);
const regent = new Noble('Regent', 4, 'purple');
deckNobles.push(regent);
const rival = new Noble('Rival Executioner', 1, 'green');
deckNobles.push(rival);
const robespierre = new Noble('Robespierre', 3, 'purple');
deckNobles.push(robespierre);
const sheriffOne = new Noble('Sheriff 1', 1, 'green');
deckNobles.push(sheriffOne);
const sheriffTwo = new Noble('Sheriff 2', 1, 'green');
deckNobles.push(sheriffTwo);
const spy = new Noble('Master Spy', 4, 'red');
deckNobles.push(spy);
const tax = new Noble('Tax Collector', 2, 'green');
deckNobles.push(tax);
const tragic = new Noble('Tragic Figure', -1, 'gray');
deckNobles.push(tragic);
const victim = new Noble('Innocent Victim', -1, 'gray');
deckNobles.push(victim);